version: "3.7"

services:
    database:
        image: postgres
        container_name: MyFinances_db
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=MyFinances
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: MyFinances_api
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database

volumes:
    pgdata:
        driver: local